<a href="https://colab.research.google.com/github/hufsaim/T03108701/blob/main/notebook_2024/Lab02_cost_of_computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cupy as cp
import time

In [2]:
!nvidia-smi

Wed Sep 25 04:39:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P8              14W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Matrix A, vector b 정의하기 (numpy)

In [3]:
n=2
A = np.random.randint(-10,10,size=(n,n))
b = np.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

A=
 [[ 9 -2]
 [ 3  2]]
b=
 [[-6]
 [ 1]]


### Ax = b 의 solution x를 계산하기 (numpy)

In [4]:
x = np.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

solution of Ax = b: 
 [[-0.41666667]
 [ 1.125     ]]


### Matrix A, vector b를 정의하고 Ax = b의 solution x를 계산하기 (cupy - GPU활용)

In [5]:
n = 2
A = cp.random.randint(-10,10,size=(n,n))
b = cp.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

x = cp.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

A=
 [[ -3  -3]
 [-10   4]]
b=
 [[-2]
 [ 2]]
solution of Ax = b: 
 [[0.04761905]
 [0.61904762]]


### CPU를 사용한 풀이 (for large N)

In [11]:
N=10000
print(N,'x',N,' matrix:')
A = np.random.randint(-10,10,size=(N,N))
b = np.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
x=np.linalg.solve(A,b)
solve_time=time.time() -s0
print('computation time = ',solve_time,' sec')

10000 x 10000  matrix:
computation time =  16.060715436935425  sec


### GPU를 사용한 풀이 (for large N)



In [12]:
N=10000
print(N,'x',N,' matrix:')
Ac = cp.random.randint(-10,10,size=(N,N))
bc = cp.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
xc=cp.linalg.solve(Ac,bc)
solve_time=time.time() -s0
print('computation time = ',solve_time,' sec')

10000 x 10000  matrix:
computation time =  1.6484434604644775  sec


## Matrix multiplication

In [13]:
n=2
A = np.random.randint(-10,10,size=(n,n))
B = np.random.randint(-10,10,size=(n,n))
print('A=\n',A)
print('B=\n',B)

AB = np.matmul(A,B)
print('AB=\n',AB)


A=
 [[-7  4]
 [ 8  7]]
B=
 [[ 1 -5]
 [ 6  2]]
AB=
 [[ 17  43]
 [ 50 -26]]


### CPU를 사용한 AB computation (for large N)

In [14]:
N = 2000
A = np.random.randint(-10,10,size=(N,N))
B = np.random.randint(-10,10,size=(N,N))
print('shape of A: ',A.shape)
print('shape of B:',B.shape)

s0 = time.time()
AB = np.matmul(A, B)
compu_time=time.time() - s0
print('computation time = ', compu_time,' sec')

shape of A:  (2000, 2000)
shape of B: (2000, 2000)
computation time =  12.188165664672852  sec


### GPU를 사용한 AB computation (for large N)

In [15]:
N = 2000
A = cp.random.randint(-10,10,size=(N,N))
B = cp.random.randint(-10,10,size=(N,N))
print('shape of A: ',A.shape)
print('shape of B:',B.shape)

s0 = time.time()
AB = cp.matmul(A, B)
compu_time=time.time() - s0
print('computation time = ', compu_time,' sec')

shape of A:  (2000, 2000)
shape of B: (2000, 2000)
computation time =  0.00041484832763671875  sec


### Exercise
- N = 10, 100, 1000, 10000 인 경우 numpy로 Ax=b를 푸는 시간과 cupy로 Ax=b를 푸는데 걸리는 시간을 각각 5번씩 반복하여 측정하여 평균을 구해보기.
- N = 2, 20, 200, 2000 인 경우 numpy로 AB를 계산하는 시간과 cupy로 AB를 계산하는 시간을 각각 5번씩 반복하여 측정하여 평균을 구해보기.