<a href="https://colab.research.google.com/github/hufsaim/T03108701/blob/main/notebook_2024/Lab02_cost_of_computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cupy as cp
import time

## Matrix A, vector b 정의하기 (numpy)

In [2]:
n=2
A = np.random.randint(-10,10,size=(n,n))
b = np.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

A=
 [[-8  7]
 [ 9 -4]]
b=
 [[ 4]
 [-5]]


## Ax = b 의 solution x를 계산하기 (numpy)

In [3]:
x = np.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

solution of Ax = b: 
 [[-0.61290323]
 [-0.12903226]]


## Matrix A, vector b를 정의하고 Ax = b의 solution x를 계산하기 (cupy - GPU활용)

In [4]:
n = 2
A = cp.random.randint(-10,10,size=(n,n))
b = cp.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

x = cp.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

A=
 [[-10  -8]
 [  8   0]]
b=
 [[  3]
 [-10]]
solution of Ax = b: 
 [[-1.25  ]
 [ 1.1875]]


## CPU를 사용한 풀이 (for large N)

In [9]:
N=10000
print(N,'x',N,' matrix:')
A = np.random.randint(-10,10,size=(N,N))
b = np.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
x=np.linalg.solve(A,b)
solve_time=time.time() -s0
print('computation time = ',solve_time,' sec')

10000 x 10000  matrix:
computation time =  15.743062496185303  sec


## GPU를 사용한 풀이 (for large N)



In [10]:
N=10000
print(N,'x',N,' matrix:')
Ac = cp.random.randint(-10,10,size=(N,N))
bc = cp.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
xc=cp.linalg.solve(Ac,bc)
solve_time=time.time() -s0
print('computation time = ',solve_time,' sec')

10000 x 10000  matrix:
computation time =  1.6424784660339355  sec
