<a href="https://colab.research.google.com/github/hufsaim/T03108701/blob/main/notebook_2025/Lab02_cost_of_computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import cupy as cp
import time

- 이번 실습은 런타임 -> 런타임 유형변경 -> 하드웨어 가속기에서 GPU 선택(예: T4 GPU) 과정을 통해 colab에서 GPU를 활용할 수 있도록 해야 합니다.

In [2]:
!nvidia-smi

Tue Sep 30 07:54:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Matrix A, vector b 정의하기 (numpy)

In [ ]:
n=2
A = np.random.randint(-10,10,size=(n,n))
b = np.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

A=
 [[ 9 -2]
 [ 3  2]]
b=
 [[-6]
 [ 1]]


### Ax = b 의 solution x를 계산하기 (numpy)

In [ ]:
x = np.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

solution of Ax = b: 
 [[-0.41666667]
 [ 1.125     ]]


### Matrix A, vector b를 정의하고 Ax = b의 solution x를 계산하기 (cupy - GPU활용)

In [ ]:
n = 2
A = cp.random.randint(-10,10,size=(n,n))
b = cp.random.randint(-10,10,size=(n,1))
print('A=\n',A)
print('b=\n',b)

x = cp.linalg.solve(A,b)
print('solution of Ax = b: \n',x)

A=
 [[ -3  -3]
 [-10   4]]
b=
 [[-2]
 [ 2]]
solution of Ax = b: 
 [[0.04761905]
 [0.61904762]]


### Matrix A의 inverse Matrix를 계산하기 (numpy - CPU활용)

In [3]:
n = 2
A = np.random.randint(-10,10,size=(n,n))
print('A=\n',A)

A_inv = np.linalg.inv(A)
print('inverse of A=\n',A_inv)

A=
 [[-10  -4]
 [  1  -7]]
inverse of A=
 [[-0.09459459  0.05405405]
 [-0.01351351 -0.13513514]]


### Matrix A의 inverse Matrix를 계산하기 (cupy - GPU활용)


In [4]:
n = 2
A = cp.random.randint(-10,10,size=(n,n))
print('A=\n',A)

A_inv = cp.linalg.inv(A)
print('inverse of A=\n',A_inv)

A=
 [[-2 -2]
 [ 4  5]]
inverse of A=
 [[-2.5 -1. ]
 [ 2.   1. ]]


### CPU를 사용한 풀이 (for large N)

In [5]:
N = 10000
print(N,'x',N,' matrix:')
A = np.random.randint(-10,10,size=(N,N))
b = np.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
x = np.linalg.solve(A,b)
solve_time = time.time() -s0
print('computation time (solution of linear equation)= ',solve_time,' sec')

s0 = time.time()
x = np.linalg.inv(A)
solve_time = time.time() -s0
print('computation time (inverse matrix) = ',solve_time,' sec')

10000 x 10000  matrix:
computation time (solution of linear equation)=  23.524182558059692  sec
computation time (inverse matrix) =  87.14442348480225  sec


### GPU를 사용한 풀이 (for large N)



In [6]:
N = 10000
print(N,'x',N,' matrix:')
Ac = cp.random.randint(-10,10,size=(N,N))
bc = cp.random.randint(-10,10,size=(N,1))
#print('\ndet(A)=',np.linalg.det(A))

s0 = time.time()
xc = cp.linalg.solve(Ac,bc)
solve_time = time.time() -s0
print('computation time (solution of linear equation) = ',solve_time,' sec')

s0 = time.time()
xc = cp.linalg.inv(Ac)
solve_time = time.time() -s0
print('computation time (inverse matrix) = ',solve_time,' sec')

10000 x 10000  matrix:
computation time (solution of linear equation) =  3.199028491973877  sec
computation time (inverse matrix) =  2.1004598140716553  sec


## Matrix multiplication

In [7]:
n = 2
A = np.random.randint(-10,10,size=(n,n))
B = np.random.randint(-10,10,size=(n,n))
print('A=\n',A)
print('B=\n',B)

AB = np.matmul(A,B)
print('AB=\n',AB)


A=
 [[ 2 -3]
 [ 8  4]]
B=
 [[-8  1]
 [ 9  6]]
AB=
 [[-43 -16]
 [-28  32]]


### CPU를 사용한 AB computation (for large N)

In [8]:
N = 2000
A = np.random.randint(-10,10,size=(N,N))
B = np.random.randint(-10,10,size=(N,N))
print('shape of A: ',A.shape)
print('shape of B:',B.shape)

s0 = time.time()
AB = np.matmul(A, B)
compu_time=time.time() - s0
print('computation time = ', compu_time,' sec')

shape of A:  (2000, 2000)
shape of B: (2000, 2000)
computation time =  13.391748189926147  sec


### GPU를 사용한 AB computation (for large N)

In [9]:
N = 2000
A = cp.random.randint(-10,10,size=(N,N))
B = cp.random.randint(-10,10,size=(N,N))
print('shape of A: ',A.shape)
print('shape of B:',B.shape)

s0 = time.time()
AB = cp.matmul(A, B)
compu_time=time.time() - s0
print('computation time = ', compu_time,' sec')

shape of A:  (2000, 2000)
shape of B: (2000, 2000)
computation time =  2.2283873558044434  sec


## Exercise
- N = 10, 100, 1000, 10000 인 경우 numpy로 Ax=b를 푸는 시간과 cupy로 Ax=b를 푸는데 걸리는 시간을 각각 5번씩 반복하여 측정하여 평균을 구해보기.
- N = 10, 100, 1000, 10000 인 경우 numpy로 A의 inverse matrix를 구하는 시간과 cupy로 A의 inverse matrix를 구하는 데 걸리는 시간을 각각 5번씩 반복하여 측정하여 평균을 구해보기.
- N = 2, 20, 200, 2000 인 경우 numpy로 AB를 계산하는 시간과 cupy로 AB를 계산하는 시간을 각각 5번씩 반복하여 측정하여 평균을 구해보기.