<a href="https://colab.research.google.com/github/hufsaim/T03108701/blob/main/notebook_2025/Lab03_Markov_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Markov matrix
N명의 학생의 홈페이지가 있고, 각 학생의 홈페이지에는 다른 학생들의 홈페이지로 이동할 수 있는 링크를 포함하고 있다고 하자.

예를 들어 3명의 학생 철수, 민수, 영희가 있을 때에
- 철수의 홈페이지에는 철수, 민수에 대한 링크가 있고,
- 민수의 홈페이지에는 철수, 영희에 대한 링크가 있고,
- 영희의 홈페이지에는 철수, 민수, 영희에 대한 링크가 있다고 하자.

각 matrix의 column을 해당 학생의 홈페이지에서 다른 학생의 홈페이지로 이동할 수 있는 확률이라고 하고, 각 링크로 이동할 확률은 균일하다고 하면 우리는 해당정보를 요약하는 다음과 같은 3 x 3 matrix A를 정의할 수 있다.

$A =
 \begin{pmatrix}
  1/2 & 1/2 & 1/3 \\
  1/2 & 0  & 1/3 \\
  0 & 1/2 & 1/3
 \end{pmatrix}$

각 column, row는 순서대로 철수, 민수, 영희를 나타낼 때, $A^2$, $A^3$, ... , $A^{100}$ 이 어떤 정보를 주는 지 생각하여 보자.

In [2]:
A = np.array([[1/2, 1/2, 1/3],
              [1/2, 0, 1/3],
              [0, 1/2, 1/3]])
print(A)

[[0.5        0.5        0.33333333]
 [0.5        0.         0.33333333]
 [0.         0.5        0.33333333]]


In [3]:
print(np.linalg.matrix_power(A,2))

[[0.5        0.41666667 0.44444444]
 [0.25       0.41666667 0.27777778]
 [0.25       0.16666667 0.27777778]]


In [4]:
print(np.linalg.matrix_power(A,3))

[[0.45833333 0.47222222 0.4537037 ]
 [0.33333333 0.26388889 0.31481481]
 [0.20833333 0.26388889 0.23148148]]


In [5]:
print(np.linalg.matrix_power(A,5))

[[0.46064815 0.46334877 0.46090535]
 [0.31134259 0.30131173 0.30889918]
 [0.22800926 0.23533951 0.23019547]]


In [6]:
A100 = np.linalg.matrix_power(A,100)
print(A100)

[[0.46153846 0.46153846 0.46153846]
 [0.30769231 0.30769231 0.30769231]
 [0.23076923 0.23076923 0.23076923]]


## Eigenvalues, eigenvectors of Markov matrix
위에서 정의한 matrix A의 eigenvalue와 eigenvector를 구하여 $A^{100}$의 결과와 함께 이해하여 보자.

In [7]:
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)
print(eigvecs)

[-0.38379594  1.          0.21712927]
[[-0.24104363 -0.76822128 -0.59880267]
 [ 0.79611302 -0.51214752 -0.18130286]
 [-0.55506939 -0.38411064  0.78010553]]


In [8]:
eigvecs1 = eigvecs[:,np.argmax(eigvals)]
print(eigvecs1)

[-0.76822128 -0.51214752 -0.38411064]


In [9]:
r = A100[:,1]/eigvecs1

In [10]:
print(eigvecs1 * (r[0]))

[0.46153846 0.30769231 0.23076923]


In [11]:
print(A100[:,0])

[0.46153846 0.30769231 0.23076923]
